hw2
shavkunov/Java pull request #2
Opened 2016-09-17 14:54 UTC by shavkunov

2016-09-18 11:30 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +import java.util.Arrays;
лучше, чтобы Matrix тоже был в каком-то пакете

2016-09-18 11:31 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +    private class Column implements Comparable<Column>{
перед { нужен пробел

2016-09-18 11:32 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +     */
комментарии имеет смысл писать над каждым полем отдельно. а то ни JavaDoc, ни среда разработки их не найдут и не смогут показывать во всплывающих подсказках

2016-09-18 11:32 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +        public int compareTo (Column col) {
пробел перед скобкой лишний

2016-09-18 11:33 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +            data[x] = y;
x и y ничего не говорят о назначении переменных, лучше сделать и имена более говорящими

2016-09-18 11:33 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +        int[] data;
private

2016-09-18 11:34 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +                data[j].set(i, j*size + i);
арифметические операции практичеки всегда выделяются пробелами:
```java
data[j].set(i, j * size + i);
```

2016-09-18 11:37 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +    private int y;
вспомогательные переменные, необходимые одному-двум методам, делать полями класса плохо --- ненужная зависимость по данным между вызовами, что может быть очень плохо, если кто-нибудь когда-нибудь решит это распараллелить. лучше оставить их локальными переменными и передавать как параметры, если совсем плохо --- сделать отдельный класс

2016-09-18 11:38 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +        x = y = size / 2;
присваивания лучше на отдельных строчках, их будет труднее не заметить

2016-09-18 11:39 UTC, yurii-litvinov commented on Matrix/src/main/java/Matrix.java
> +        int dy, dx;
объявления переменных тоже лучше на отдельных строчках, и, на самом деле, внутри for-а (чтобы ограничить их область видимости)

2016-09-18 11:41 UTC, yurii-litvinov commented on Matrix/src/test/java/MatrixTest.java
> +        assertTrue(answerVect.equals(myAnswer));
лучше assertEquals, будет более содержательное сообщение, если тест не пройдёт

2016-09-18 11:42 UTC, yurii-litvinov commented on Matrix/src/test/java/MatrixTest.java
> +        int[][] mydata = { {2, 1, 0}, {5, 4, 3}, {8, 7, 6} };
myData

2016-09-18 11:42 UTC, yurii-litvinov commented on Matrix/src/test/java/MatrixTest.java
> +
две пустые строки подряд --- плохо

2016-09-18 11:43 UTC, yurii-litvinov requested changes

2016-09-20 20:06 UTC, yurii-litvinov commented
гитхаб говорит, что есть конфликт с мастером, который надо заресолвить перед мерджем

2016-09-20 20:08 UTC, yurii-litvinov commented on Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java
> + * Реализация класса ru.spbau.shavkunov.hw2.Matrix.
капитан очевидность :) тут лучше писать, что делает этот класс

2016-09-20 20:09 UTC, yurii-litvinov commented on Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java
> +    private int size;
массив ведь сам знает свой размер

2016-09-20 20:11 UTC, yurii-litvinov commented on Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java
> +    private Vector<Integer> tour;
это очень сильно похоже на локальную переменную метода spiralTour. она правда является частью состояния класса, входит в его инвариант и её важно хранить от вызова метода к вызову?

2016-09-20 20:12 UTC, yurii-litvinov requested changes
доисправляйте, пожалуйста

2016-09-20 20:33 UTC, shavkunov commented
Я исправил и изменения закоммитил.У меня возникли некоторые проблемы с гитом, я много раз чего-то там создавал и удалял. Вроде сейчас все нормально, но у меня один раз тоже спросили по поводу конфликта, когда я нажал разрешить github не сделал НИЧЕГО. Т.е. там прям и отображалось - 0 изменений. :)К чему я говорю: это вы должны разрешить конфликт или я должен это сделать?(если я, то скажите как)20.09.2016, 23:12, "Yurii Litvinov" <notifications@github.com>:@yurii-litvinov requested changes on this pull request.

доисправляйте, пожалуйста

In Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java:
> @@ -0,0 +1,271 @@
+package ru.spbau.shavkunov.hw2;
+
+import java.util.Arrays;
+import java.util.Vector;
+
+/**
+ * Реализация класса ru.spbau.shavkunov.hw2.Matrix.

капитан очевидность :) тут лучше писать, что делает этот класс



In Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java:
> + */
+public class Matrix {
+    /**
+     * Матрица хранится как список столбцов.
+     */
+    private Column[] data;
+
+    /**
+     * Переменная хранящая обход матрица по спирали.
+     */
+    private Vector<Integer> tour;
+
+    /**
+     * Размер квадратной матрицы.
+     */
+    private int size;

массив ведь сам знает свой размер



In Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java:
> +
+/**
+ * Реализация класса ru.spbau.shavkunov.hw2.Matrix.
+ *
+ * @author mikhail shavkunov
+ */
+public class Matrix {
+    /**
+     * Матрица хранится как список столбцов.
+     */
+    private Column[] data;
+
+    /**
+     * Переменная хранящая обход матрица по спирали.
+     */
+    private Vector<Integer> tour;

это очень сильно похоже на локальную переменную метода spiralTour. она правда является частью состояния класса, входит в его инвариант и её важно хранить от вызова метода к вызову?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- С уважением, Михаил Шавкунов 

2016-09-20 20:58 UTC, yurii-litvinov commented
Конфликты ресолвите по идее Вы :) Разработчик отвечает за поддержание своего бранча в актуальном состоянии (что, кстати, для реального проекта может быть сложно, часто изменения появляются быстрее, чем успеваешь обновлять бранч). Как --- переключаетесь на этот бранч (hw2), делаете git merge master (или git pull origin master), оно должно сообщить о конфликтах. Разрешаете их (вручную, редактруя файлы с конфликтами, либо каким-нить тулом типа той же Идеи), коммитите, пушите. У Вас на самом деле конфликты в основном в проектных файлах, можно при ресолве указать использовать Ваши текущие (git checkout --ours <имя файла>), вот в Main.java может быть что-нить более содержательное. Вот годная короткая инструкция: https://easyengine.io/tutorials/git/git-resolve-merge-conflicts/. И я завтра на паре ещё расскажу поподробнее про гит вообще, а то, как я понял, вам всем особо не рассказывали.

2016-09-25 07:37 UTC, yurii-litvinov commented on Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java
> +     * Перегразка метода equals, сравнение матриц.
Перегразка --- опечатка

2016-09-25 07:37 UTC, yurii-litvinov commented on Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java
> +    /**
тут надо бы summary

2016-09-25 07:38 UTC, yurii-litvinov commented on Matrix/src/test/java/ru/spbau/shavkunov/hw2/MatrixTest.java
> +        Assert.assertEquals(myAnswer.toString(), "[0]");
тут аргументы наоборот, сначала expected, потом actual

2016-09-25 07:39 UTC, yurii-litvinov commented on Matrix/src/main/java/ru/spbau/shavkunov/hw2/Matrix.java
> +        Matrix input = (Matrix) in;
по-хорошему, надо проверять тип объекта in, вдруг кто-нить передаст не матрицу?

2016-09-25 07:41 UTC, yurii-litvinov commented on Matrix/src/test/java/ru/spbau/shavkunov/hw2/MatrixTest.java
> +        Vector answerVect = new Vector(Arrays.asList(answer1));
тут ругается на unchecked, надо писать параметр-тип шаблона, чтобы так не было

2016-09-25 07:42 UTC, yurii-litvinov approved these changes
есть некоторые замечания, но в целом всё нравится, зачтена. А замечания учтите в следующих задачах

2016-09-25 07:42 UTC, merged